
package chatbot2;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.applet.AudioClip;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author andre
 */
public class Main extends javax.swing.JFrame {
    String pregunta, respuesta,preguntagenerada,frase;
    boolean reproducciendo=false;
     AudioClip sonido1, sonido2, alive;

    
    public Main() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla = new javax.swing.JTextArea();
        name = new javax.swing.JLabel();
        online = new javax.swing.JLabel();
        Enviar = new javax.swing.JButton();
        Enseñar = new javax.swing.JButton();
        Texto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantalla.setBackground(new java.awt.Color(204, 204, 204));
        pantalla.setColumns(20);
        pantalla.setRows(5);
        jScrollPane1.setViewportView(pantalla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 450, 220));

        name.setFont(new java.awt.Font("Segoe UI Variable", 0, 36)); // NOI18N
        name.setText("RX-78");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 50));

        online.setText("Online");
        jPanel1.add(online, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        Enviar.setBackground(new java.awt.Color(0, 51, 255));
        Enviar.setForeground(new java.awt.Color(255, 255, 255));
        Enviar.setText("Enviar");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });
        jPanel1.add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 80, -1));

        Enseñar.setBackground(new java.awt.Color(0, 51, 204));
        Enseñar.setForeground(new java.awt.Color(255, 255, 255));
        Enseñar.setText("Enseñar");
        Enseñar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnseñarActionPerformed(evt);
            }
        });
        jPanel1.add(Enseñar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        Texto.setBackground(new java.awt.Color(255, 255, 255));
        Texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextoKeyTyped(evt);
            }
        });
        jPanel1.add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 450, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gundam_logo_2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:
         Thread hilo = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
        pregunta=Texto.getText();
        respuesta=(new BuscaDatos().translate(Texto.getText()));
        preguntagenerada=(new BuscaDatos().translate(generarpregunta()));
        pantalla.append("Usted: "+Texto.getText() +"\n");
        if (respuesta.equalsIgnoreCase("")){
        pantalla.append("RX 78: Podrias enseñarme que debo responder si me dicen: '"+pregunta+"' por favor (si/no)\n");
        String respuestUsuario= JOptionPane.showInputDialog("Deseas enseñarle?(si/no)");
        if (respuestUsuario.equalsIgnoreCase("si")){
             String respuestUsuarioPregunta= JOptionPane.showInputDialog("Que responder a '"+pregunta+"'");
             Leer aprender =new Leer();
             String nuevapalabra=aprender.preguntanueva(pregunta,respuestUsuarioPregunta);
             aprender.guardar(aprender.leertxt("datos.txt"), nuevapalabra);   
        }
    }
        Texto.setText("");
        animacionEscribir(respuesta);
        int probabilidad=mitadProbabilidad();
        //System.out.println(probabilidad);
        if(probabilidad>5){
        //  System.out.println("entra");
             animacionpregunta(preguntagenerada);
             if (preguntagenerada.equalsIgnoreCase("pongamos musica") && reproducciendo != true){
                 alive =java.applet.Applet.newAudioClip(getClass().getResource("./alive.wav"));
                 alive.play();
             }
             
        }   
        } catch (Exception e) {
        }
        }
        });
        hilo.start();
    }//GEN-LAST:event_EnviarActionPerformed
    public String tratarText(){
        frase = Texto.getText();
        return frase;}
    
    private void EnseñarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnseñarActionPerformed
        // TODO add your handling code here:
        String UsuarioPregunta= JOptionPane.showInputDialog("Ingrese pregunta");
         String respuestUsuarioPregunta= JOptionPane.showInputDialog("Que responder a '"+ UsuarioPregunta+"'");
         Leer aprender =new Leer();
         String nuevapalabra=aprender.preguntanueva(UsuarioPregunta,respuestUsuarioPregunta);
         aprender.guardar(aprender.leertxt("datos.txt"), nuevapalabra);   
    }//GEN-LAST:event_EnseñarActionPerformed

    private void TextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextoKeyTyped
        // TODO add your handling code here:
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER) {
              Enviar.doClick();
        }
    }//GEN-LAST:event_TextoKeyTyped

   public String generarpregunta(){
        int numero;
        numero = (int) (Math.random() * 9) + 1;
        String preguntaAleatoria = Integer.toString(numero);
        String preguntacompletada= preguntaAleatoria+"p";
        return preguntacompletada;
    }
   
   public int mitadProbabilidad(){
         int numero;
        numero = (int) (Math.random() * 9) + 1;
        return numero;
    }
   
   public void animacionEscribir(String respuestaxd) throws InterruptedException, URISyntaxException, IOException{
        sonido1 =java.applet.Applet.newAudioClip(getClass().getResource("./mensajellegada.wav"));
        sonido2 =java.applet.Applet.newAudioClip(getClass().getResource("./pop.wav"));
        Thread.sleep(generarRandom());
        online.setForeground(Color.blue);
        sonido2.play();
        online.setText("Visto");
        Thread.sleep(generarRandom());
        online.setText("Escribiendo"); 
        Thread.sleep(generarRandom());
        online.setText("");
        sonido1.play();
        pantalla.append("RX 78: "+ respuestaxd+"\n");
          if(pregunta.equalsIgnoreCase("reproducir musica")){
            reproducciendo=true;
              Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=I_izvAbhExY"));
          //  alive =java.applet.Applet.newAudioClip(getClass().getResource("./alive.wav"));
           // alive.play();
        }
        //  System.out.println(generarRandom());
    }
      public void animacionpregunta(String respuestaxd) throws InterruptedException{
        sonido1 =java.applet.Applet.newAudioClip(getClass().getResource("./mensajellegada.wav"));
        Thread.sleep(1500);
        online.setText("Escribiendo"); 
        Thread.sleep(1000);
        online.setText("");
        sonido1.play();
        pantalla.append("RX 78: "+ respuestaxd+"\n");
    }
      public int generarRandom(){
        int numero;
        numero = (int) (Math.random() * 4000) + 1000;
        return numero;
        
    }
    
      public void fijarTexto(){
         pantalla.append("Maquina: "+ respuesta+"\n");
        Texto.setText("");
    }
      private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
          
    }
      
      public JButton enviarPresionado(){
        return Enviar;
    }
    public void setPanatalla(){
        pantalla.append("Maquina: "+ respuesta+"\n");
    }
    public JTextArea regresaPantalla(){
        return pantalla;
    }
    

    public JTextField regresaTexto(){
        return Texto;
    }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enseñar;
    private javax.swing.JButton Enviar;
    private javax.swing.JTextField Texto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel online;
    private javax.swing.JTextArea pantalla;
    // End of variables declaration//GEN-END:variables
}
